//------------------------------------------------------------------------------
// Requirements
//------------------------------------------------------------------------------

import { noArrayMethods } from './rules/noArrayMethods'

//------------------------------------------------------------------------------
// Plugin Definition
//------------------------------------------------------------------------------

// import all rules in lib/rules
const rules = {
    'no-array-methods': noArrayMethods,
}
const configs = {
    recommended: {
        root: true,
        parser: '@typescript-eslint/parser',
        plugins: [
            '@typescript-eslint',
            'simple-import-sort',
            'functional',
            'unicorn',
            '@fanclub',
        ],
        extends: [
            'eslint:recommended',
            'plugin:@typescript-eslint/recommended',
            'plugin:functional/external-recommended',
            'plugin:functional/no-object-orientation',
            'plugin:unicorn/recommended',
            'prettier',
        ],
        env: {
            node: true,
        },
        rules: {
            'simple-import-sort/imports': 'error',
            'simple-import-sort/exports': 'error',
            'arrow-body-style': ['warn', 'as-needed'],
            '@typescript-eslint/ban-ts-comment': 'error',
            'no-console': 'error',
            '@typescript-eslint/no-unused-vars': 'error',
            'unicorn/filename-case': ['warn', { case: 'camelCase' }],
            '@fanclub/no-array-methods': 'warn',

            // setting all rules from "plugin:unicorn/recommended" to warnings only for migration
            'unicorn/better-regex': 'warn',
            'unicorn/catch-error-name': 'warn',
            'unicorn/consistent-destructuring': 'warn',
            'unicorn/consistent-function-scoping': 'warn',
            'unicorn/empty-brace-spaces': 'warn',
            'unicorn/error-message': 'warn',
            'unicorn/escape-case': 'warn',
            'unicorn/expiring-todo-comments': 'warn',
            'unicorn/explicit-length-check': 'warn',
            'unicorn/import-style': 'warn',
            'unicorn/new-for-builtins': 'warn',
            'unicorn/no-abusive-eslint-disable': 'warn',
            'unicorn/no-array-callback-reference': 'warn',
            'unicorn/no-array-for-each': 'warn',
            'unicorn/no-array-method-this-argument': 'warn',
            'unicorn/no-array-push-push': 'warn',
            'unicorn/no-array-reduce': 'warn',
            'unicorn/no-await-expression-member': 'warn',
            'unicorn/no-console-spaces': 'warn',
            'unicorn/no-document-cookie': 'warn',
            'unicorn/no-empty-file': 'warn',
            'unicorn/no-for-loop': 'warn',
            'unicorn/no-hex-escape': 'warn',
            'unicorn/no-instanceof-array': 'warn',
            'unicorn/no-invalid-remove-event-listener': 'warn',
            'unicorn/no-lonely-if': 'warn',
            'unicorn/no-nested-ternary': 'warn',
            'unicorn/no-new-array': 'warn',
            'unicorn/no-new-buffer': 'warn',
            'unicorn/no-null': 'warn',
            'unicorn/no-object-as-default-parameter': 'warn',
            'unicorn/no-process-exit': 'warn',
            'unicorn/no-static-only-class': 'warn',
            'unicorn/no-thenable': 'warn',
            'unicorn/no-this-assignment': 'warn',
            'unicorn/no-unreadable-array-destructuring': 'warn',
            'unicorn/no-unreadable-iife': 'warn',
            'unicorn/no-useless-fallback-in-spread': 'warn',
            'unicorn/no-useless-length-check': 'warn',
            'unicorn/no-useless-promise-resolve-reject': 'warn',
            'unicorn/no-useless-spread': 'warn',
            'unicorn/no-useless-switch-case': 'warn',
            'unicorn/no-useless-undefined': 'warn',
            'unicorn/no-zero-fractions': 'warn',
            'unicorn/number-literal-case': 'warn',
            'unicorn/numeric-separators-style': 'warn',
            'unicorn/prefer-add-event-listener': 'warn',
            'unicorn/prefer-array-find': 'warn',
            'unicorn/prefer-array-flat': 'warn',
            'unicorn/prefer-array-flat-map': 'warn',
            'unicorn/prefer-array-index-of': 'warn',
            'unicorn/prefer-array-some': 'warn',
            'unicorn/prefer-code-point': 'warn',
            'unicorn/prefer-date-now': 'warn',
            'unicorn/prefer-default-parameters': 'warn',
            'unicorn/prefer-dom-node-append': 'warn',
            'unicorn/prefer-dom-node-dataset': 'warn',
            'unicorn/prefer-dom-node-remove': 'warn',
            'unicorn/prefer-dom-node-text-content': 'warn',
            'unicorn/prefer-export-from': 'warn',
            'unicorn/prefer-includes': 'warn',
            'unicorn/prefer-keyboard-event-key': 'warn',
            'unicorn/prefer-logical-operator-over-ternary': 'warn',
            'unicorn/prefer-math-trunc': 'warn',
            'unicorn/prefer-modern-dom-apis': 'warn',
            'unicorn/prefer-modern-math-apis': 'warn',
            'unicorn/prefer-module': 'warn',
            'unicorn/prefer-native-coercion-functions': 'warn',
            'unicorn/prefer-negative-index': 'warn',
            'unicorn/prefer-node-protocol': 'warn',
            'unicorn/prefer-number-properties': 'warn',
            'unicorn/prefer-object-from-entries': 'warn',
            'unicorn/prefer-optional-catch-binding': 'warn',
            'unicorn/prefer-prototype-methods': 'warn',
            'unicorn/prefer-query-selector': 'warn',
            'unicorn/prefer-reflect-apply': 'warn',
            'unicorn/prefer-regexp-test': 'warn',
            'unicorn/prefer-set-has': 'warn',
            'unicorn/prefer-spread': 'warn',
            'unicorn/prefer-string-slice': 'warn',
            'unicorn/prefer-string-starts-ends-with': 'warn',
            'unicorn/prefer-string-trim-start-end': 'warn',
            'unicorn/prefer-switch': 'warn',
            'unicorn/prefer-ternary': 'warn',
            'unicorn/prefer-top-level-await': 'warn',
            'unicorn/prefer-type-error': 'warn',
            'unicorn/prevent-abbreviations': 'warn',
            'unicorn/relative-url-style': 'warn',
            'unicorn/require-array-join-separator': 'warn',
            'unicorn/require-number-to-fixed-digits-argument': 'warn',
            'unicorn/template-indent': 'warn',
            'unicorn/text-encoding-identifier-case': 'warn',
            'unicorn/throw-new-error': 'warn',

            // set all rules from 'plugin:functional/no-object-orientation' and 'plugin:functional/external-recommended' to warning
            'functional/no-this-expression': 'warn',
            'functional/no-class': 'warn',
            'functional/no-mixed-type': 'warn',
            'prefer-const': 'warn',
            'no-param-reassign': 'warn',
            'no-var': 'warn',
            '@typescript-eslint/switch-exhaustiveness-check': 'warn',
        },
    },
}

module.exports = {
    rules,
    configs,
}
